version: 2

jobs:
  deploy:
    docker:
      - image: circleci/clojure:lein-2.9.0
    steps:
      - run:
          name: Clone docs          
          command: |
            git clone https://${GH_TOKEN}@github.com/kit-clj/kit-clj.github.io.git
            cd kit-clj.github.io
      - run:
          name: build site          
          command: |
            cd kit-clj.github.io
            lein run
      - run:
          name: push to GH pages          
          command: |
            cd kit-clj.github.io
            rm -rf docs
            mv static docs
            git config user.email "dmitri.sotnikov@gmail.com"
            git config user.name "Dmitri Sotnikov"
            git add --all
            if [ -n "$(git status --porcelain)" ]; then git commit -a -m "Circle #$CIRCLE_BUILD_NUM" && git push --force origin master; fi  

workflows:
  version: 2
  deploy_site:
    jobs:
      - deploy

